import Foundation
import Observation

@Observable
@MainActor
final class SearchViewModel {
    var query: String = ""
    var searchResults: [ContactSearchResult] = []
    var goals: [Goal] = []
    /// Keyed by goal.id — populated after loadGoals() completes.
    var goalMatches: [UUID: [GoalContactMatch]] = [:]
    var isSearching: Bool = false
    var isLoadingGoals: Bool = false
    var error: Error? = nil

    private let service = SupabaseService.shared

    // MARK: - Goals

    func loadGoals() async {
        guard let userId = await service.currentUserId else { return }
        isLoadingGoals = true
        defer { isLoadingGoals = false }
        do {
            goals = try await service.fetchGoals(userId: userId)
            await loadGoalMatches(userId: userId)
        } catch {
            self.error = error
        }
    }

    func addGoal(text: String) async {
        guard let userId = await service.currentUserId else { return }
        do {
            let goal = try await service.createGoal(userId: userId, text: text)
            goals.insert(goal, at: 0)
            // Embedding is generated by GeminiService in a background Task kicked off by the caller.
        } catch {
            self.error = error
        }
    }

    func deactivateGoal(_ goal: Goal) async {
        do {
            try await service.deactivateGoal(id: goal.id)
            goals.removeAll { $0.id == goal.id }
            goalMatches.removeValue(forKey: goal.id)
        } catch {
            self.error = error
        }
    }

    // MARK: - Semantic Search

    /// Searches contacts using a pre-computed embedding from GeminiService.
    /// The caller is responsible for embedding `query` before calling this method.
    func searchContacts(embeddedQuery: [Float]) async {
        guard let userId = await service.currentUserId else { return }
        isSearching = true
        defer { isSearching = false }
        do {
            searchResults = try await service.matchContacts(
                queryEmbedding: embeddedQuery,
                userId: userId
            )
        } catch {
            self.error = error
        }
    }

    // MARK: - Private

    private func loadGoalMatches(userId: UUID) async {
        await withTaskGroup(of: (UUID, [GoalContactMatch]).self) { group in
            for goal in goals where goal.active {
                group.addTask { [service] in
                    let matches = (try? await service.matchContactsForGoal(
                        goalId: goal.id,
                        userId: userId
                    )) ?? []
                    return (goal.id, matches)
                }
            }
            for await (goalId, matches) in group {
                goalMatches[goalId] = matches
            }
        }
    }
}
